---
galaxy_info:
  role_name: win2025_cis_hardening
  author: GMS - Banco Solidario
  description: >-
    CIS Microsoft Windows Server 2025 Benchmark v2.1.0 hardening
    (Level 1 + Level 2, Member Server profile).
  license: Proprietary
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - "2025"
  galaxy_tags:
    - cis
    - hardening
    - security
    - windows

dependencies: []
